apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: echo-server
  labels:
    tier: frontend
spec:
  replicas: 4
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: echo
        image: registry.cluster.wik.cloud/public/echo

---

apiVersion: v1
kind: Service
metadata:
  name: echo-loadbalancer
spec:
  selector:
    tier: frontend
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
