apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "echo.fullname" . }}-deployment
  labels:
    tier: frontend
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
{{ .Values.deployment.containers | toYaml | nindent 8 }}
