apiVersion: v1
kind: Service
metadata:
  name: {{ include "echo.fullname" . }}-loadbalancer
spec:
  selector:
    tier: frontend
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}
