# Default values for echo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

ingress:
  host: cppisthebest.com

deployment: 
  containers:
    - name: echo
      image: registry.cluster.wik.cloud/public/echo
